Repository Penguinification/dd2480-ci-server, pull requests merged in 2023-02, with the labels that each got.

#3 Implement simple server
  server.py
Labels: enhancement

#11 Add support for Python syntax checking
  src/server.py
  src/test/invalid_files/hello_world_invalid.py
  src/test/test_server.py
  src/test/valid_files/hello_world.py
Labels: enhancement

#13 Add automatic test execution
  pytest.ini
  src/server.py
  src/test/invalid_files/invalid_add.py
  src/test/invalid_files/test_invalid_add.py
  src/test/test_server.py
  src/test/valid_files/add.py
  src/test/valid_files/test_add.py
Labels: enhancement

#15 Change port used by temporary unit test servers
  src/test/test_server.py
Labels: bug

#19 Make parser ignore test directory
  src/server.py
  src/test/test_server.py
Labels: bug

#20 Implement setting commit status
  src/server.py
  src/test/test_server.py
Labels: enhancement

#23 Update README
  README.md
Labels: documentation

#27 Update README.md with essence description
  README.md
Labels: documentation
